import org.apache.hadoop.security.protocolPB.RefreshUserMappingsProtocolClientSideTranslatorPB;
public class FunctionUse15596 {
public void funcUse() {
RefreshUserMappingsProtocolClientSideTranslatorPB refreshusermappingsprotocolclientsidetranslatorpb = new RefreshUserMappingsProtocolClientSideTranslatorPB();
refreshusermappingsprotocolclientsidetranslatorpb.isMethodSupported(null);
}
}