import org.apache.hadoop.ipc.proto.GenericRefreshProtocolProtos.GenericRefreshResponseCollectionProtoOrBuilder;
public class FunctionUse8864 {
public void funcUse() {
GenericRefreshResponseCollectionProtoOrBuilder genericrefreshresponsecollectionprotoorbuilder = new GenericRefreshResponseCollectionProtoOrBuilder();
genericrefreshresponsecollectionprotoorbuilder.getResponsesOrBuilderList();
}
}